// <auto-generated />
using System;
using CitiWatch.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiWatch.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250828222512_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiWatch.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("IsDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IsDeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("702f9de1-aeec-4c46-3f58-6008a912f8ff"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 75, DateTimeKind.Utc).AddTicks(9086),
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Road"
                        },
                        new
                        {
                            Id = new Guid("c7b0f9d7-5f70-4e94-cb01-4d84cbf52593"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 75, DateTimeKind.Utc).AddTicks(9678),
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Waste"
                        },
                        new
                        {
                            Id = new Guid("19148c45-17a2-9b50-a242-411e8d17be41"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 75, DateTimeKind.Utc).AddTicks(9681),
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electricity"
                        });
                });

            modelBuilder.Entity("CitiWatch.Domain.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("IsDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IsDeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("CitiWatch.Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("IsDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IsDeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d31005e0-1534-6d66-45d1-580ac521784e"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 74, DateTimeKind.Utc).AddTicks(6165),
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("2b54f7da-c2cf-238c-8529-34aebfda96cb"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 74, DateTimeKind.Utc).AddTicks(6953),
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Submitted"
                        },
                        new
                        {
                            Id = new Guid("650f0f70-a108-af4b-b9db-92ce2cf633ae"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 74, DateTimeKind.Utc).AddTicks(6957),
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Resolved"
                        });
                });

            modelBuilder.Entity("CitiWatch.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("IsDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IsDeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76d32438-b3de-0d09-43be-620c377e822a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Createdon = new DateTime(2025, 8, 28, 22, 25, 10, 76, DateTimeKind.Utc).AddTicks(923),
                            Email = "SuperAdmin",
                            FullName = "",
                            IsDeleted = false,
                            IsDeletedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$.vCYWiCOAuf.t/.fOGHGeeeEcTxmXeeBqGxQRoiMlkyrLmjJz0epu",
                            Role = 1
                        });
                });

            modelBuilder.Entity("CitiWatch.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("CitiWatch.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitiWatch.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitiWatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
